import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import MagicString from "magic-string";
import type { HmrContext } from "vite";
import { describe, expect, it } from "vitest";
import { createLocatorVitePlugin } from "../../src/integration/vite-plugin.js";
import { ManifestStore } from "../../src/manifest/store.js";
import { LocatorSettingsStore } from "../../src/settings/store.js";
import {
  LOCATOR_ENDPOINT,
  LOCATOR_SESSION_ENDPOINT,
  LOCATOR_SETTINGS_ENDPOINT
} from "../../src/shared/contracts.js";

describe("createLocatorVitePlugin", () => {
  it("runs before Astro and injects source metadata into raw Astro code", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const file = path.join(root, "src", "Card.astro");
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, "<article>Card</article>", "utf8");
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token"
    });
    const load = plugin.load;

    expect(plugin.enforce).toBe("pre");
    expect(typeof load).toBe("function");
    if (typeof load !== "function") {
      throw new Error("Expected a callable load hook");
    }

    const result = await load.call(
      { addWatchFile() {} } as never,
      file
    );

    expect(result).toMatchObject({
      code: expect.stringContaining(
        'data-astro-ai-locator-file="src/Card.astro"'
      )
    });
  });

  it("injects source metadata into TSX before the React transform", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token"
    });
    const transform = plugin.transform;

    expect(typeof transform).toBe("function");
    if (typeof transform !== "function") {
      throw new Error("Expected a callable transform hook");
    }

    const result = await transform.call(
      {} as never,
      "export const Button = () => <button>Save</button>;",
      path.join(root, "src", "Button.tsx")
    );

    expect(result).toMatchObject({
      code: expect.stringContaining(
        'data-astro-ai-locator-file="src/Button.tsx"'
      )
    });
  });

  it("maps transformed TSX tag locations back to the original source", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const file = path.join(root, "src", "Breadcrumb.tsx");
    const source = [
      "export const Breadcrumb = () => (",
      "  <nav>",
      "    <BreadcrumbPage>Current</BreadcrumbPage>",
      "  </nav>",
      ");"
    ].join("\n");
    const generated = new MagicString(source);
    generated.prepend("// generated by an earlier plugin\n".repeat(8));
    const combinedMap = JSON.parse(
      generated
        .generateMap({
          source: file,
          includeContent: true,
          hires: true
        })
        .toString()
    );
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token"
    });
    const transform = plugin.transform;
    if (typeof transform !== "function") {
      throw new Error("Expected a callable transform hook");
    }

    const result = await transform.call(
      { getCombinedSourcemap: () => combinedMap } as never,
      generated.toString(),
      file
    );

    expect(result).toMatchObject({
      code: expect.stringContaining(
        'data-astro-ai-locator-loc="3:5"'
      )
    });
  });

  it("falls back to the original AST when an upstream source map is invalid", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const file = path.join(root, "src", "Card.tsx");
    const original = [
      "export const Card = () => (",
      "  <div>",
      "    <span>Title</span>",
      "    <IconBooked />",
      "  </div>",
      ");"
    ].join("\n");
    const transformed = [
      "export const Card = () => (",
      "  <IconBooked />",
      ");"
    ].join("\n");
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, original, "utf8");

    // Simulates an earlier plugin returning a map for its intermediate code
    // instead of composing that map with the original input source map.
    const invalidMapSource = new MagicString(transformed);
    const invalidCombinedMap = JSON.parse(
      invalidMapSource
        .generateMap({
          source: file,
          includeContent: true,
          hires: true
        })
        .toString()
    );
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token"
    });
    const transform = plugin.transform;
    if (typeof transform !== "function") {
      throw new Error("Expected a callable transform hook");
    }

    const result = await transform.call(
      { getCombinedSourcemap: () => invalidCombinedMap } as never,
      transformed,
      file
    );

    expect(result).toMatchObject({
      code: expect.stringContaining(
        'data-astro-ai-locator-loc="4:5"'
      )
    });
  });

  it("ignores generated manifest files without ignoring source files", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token"
    });
    const config = plugin.config;

    expect(typeof config).toBe("function");
    if (typeof config !== "function") {
      throw new Error("Expected a callable config hook");
    }
    const result = await config.call({} as never, {}, {
      command: "serve",
      mode: "development",
      isPreview: false,
      isSsrBuild: false
    });
    if (!result || typeof result !== "object") {
      throw new Error("Expected the config hook to return Vite config");
    }
    const ignored = result.server?.watch?.ignored;
    const matchers = Array.isArray(ignored) ? ignored : [ignored];
    const isIgnored = (file: string) =>
      matchers.some(
        (matcher) => typeof matcher === "function" && matcher(file)
      );

    expect(
      isIgnored(
        path.join(root, ".astro-ai-locator", "manifest.json")
      )
    ).toBe(true);
    expect(isIgnored(path.join(root, "src", "Card.tsx"))).toBe(false);
  });

  it("mounts registration and global-settings middleware separately", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const settingsStore = new LocatorSettingsStore(
      path.join(root, "test-settings.json")
    );
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token",
      settingsStore
    });
    const configureServer = plugin.configureServer;
    if (typeof configureServer !== "function") {
      throw new Error("Expected a callable configureServer hook");
    }
    const mountedPaths: string[] = [];

    configureServer.call({} as never, {
      middlewares: {
        use(route: string) {
          mountedPaths.push(route);
        }
      },
      watcher: {
        on() {},
        off() {}
      },
      httpServer: null,
      config: {
        logger: {
          error() {}
        }
      }
    } as never);

    expect(mountedPaths).toEqual([
      LOCATOR_ENDPOINT,
      LOCATOR_SETTINGS_ENDPOINT,
      LOCATOR_SESSION_ENDPOINT
    ]);
  });

  it("invalidates only entries for the changed Astro file", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const store = new ManifestStore(root);
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token",
      store
    });
    await store.reset();
    await store.upsert("astro_hash_aaaaaaaaaaaaaaaaaaaaaaaa", {
      file: "src/Card.astro",
      line: 1,
      column: 1,
      sourceTag: "article",
      domTag: "article"
    });
    await store.upsert("astro_hash_bbbbbbbbbbbbbbbbbbbbbbbb", {
      file: "src/Header.astro",
      line: 1,
      column: 1,
      sourceTag: "header",
      domTag: "header"
    });

    const hook = plugin.handleHotUpdate;
    if (typeof hook !== "function") {
      throw new Error("Expected a callable handleHotUpdate hook");
    }
    await hook.call(
      {} as never,
      { file: path.join(root, "src", "Card.astro") } as HmrContext
    );

    expect(Object.keys((await store.readSnapshot()).entries)).toEqual([
      "astro_hash_bbbbbbbbbbbbbbbbbbbbbbbb"
    ]);
  });

  it("invalidates entries for a changed TSX source file", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "astro-locator-"));
    const store = new ManifestStore(root);
    const plugin = createLocatorVitePlugin({
      root,
      sessionToken: "session-token",
      store
    });
    await store.reset();
    await store.upsert("astro_hash_aaaaaaaaaaaaaaaaaaaaaaaa", {
      file: "src/Button.tsx",
      line: 1,
      column: 29,
      sourceTag: "button",
      domTag: "button"
    });

    const hook = plugin.handleHotUpdate;
    if (typeof hook !== "function") {
      throw new Error("Expected a callable handleHotUpdate hook");
    }
    await hook.call(
      {} as never,
      { file: path.join(root, "src", "Button.tsx") } as HmrContext
    );

    expect((await store.readSnapshot()).entries).toEqual({});
  });
});
